---
apiVersion: v1
kind: Namespace
metadata:
  name: ansible-player
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mongo-config
  namespace: ansible-player
data:
  DB_ROOT_USER: ansible-player
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-root-secret
  namespace: ansible-player
type: Opaque
data:
  password: YW5zaWJsZVBsYXllciFAIw==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: ansible-player
  labels:
    app: ansible-player-mongo
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-player-mongo
  namespace: ansible-player
  labels:
    app: ansible-player-mongo
spec:
  selector:
    matchLabels:
      app: mongo-db
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.6
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 500Mi
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: DB_ROOT_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-root-secret
                  key: password
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: ansible-player
spec:
  selector:
    app: mongo-db
  type: NodePort
  ports:
    - name: mongo-db
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30000
